### ISSUE TITLE
The OSRM server returned an error:

### ISSUE THREAD

**Issue by alfdbe** [rCarto/osrm#60]
I have been trying to re-run a script which ran great a few weeks ago, but now when I call osrmIsochrone() it returns  

`The OSRM server returned an error:
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
`

I also noticed that the web app hosted at https://www.r-bloggers.com/shiny-app-drive-time-isochrones/ no longer works either? Any ideas  would be great.

**Comment by rCarto** [comment]
I can confirm the issue with the demo server. Not with my own instance. 
It may have something to do with https://github.com/Project-OSRM/osrm-backend/issues/5655

**Comment by rCarto** [comment]
That's it. `osrmIsochrone()` relies on a heavy use of the table service from OSRM. Owners of the demo server have probably added a limit on table queries. The dev version of the package should fix the issue. 
Can you please test the dev version (`remotes::install_github("rCarto/osrm")`) and report if the problem is fixed.

**Comment by alfdbe** [comment]
Yep that fixed it. Works perfectly now. Thanks for your help!

**Comment by rCarto** [comment]
Thank you for your feedback. I'll release an updated version as soon as possible.

**Comment by shriv** [comment]
Hi there, 
I installed osrm from github and still run into this issue. I've tried a 5s ping and still get this error. Any ideas when / if the server will be able to take on more load?

Thanks!

**Comment by rCarto** [comment]
That's right. The OSRM demo server is a new one and may be more, or less robust than the previous one. I've added a way for the package to repeat the request till the demo server respond with the results. It should work again. 
Note that the demo server is a demo server, it should not be intensively used. If your work relies heavily on OSRM I would suggest to use your own instance via docker containers.

**Comment by jlopezper** [comment]
I still have this issue, even after installing the dev version.

Thanks!

**Comment by rCarto** [comment]
Hum...
I don't see that, neither with the demo server, nor with a local OSRM server, nor with my remote OSRM server...

**Comment by jlopezper** [comment]
I'm sorry, I'm not able to reproduce the error. It just works now. 
Thanks and apologies

**Comment by rCarto** [comment]
No problem, it's not bad news :-)
